### ISSUE TITLE
Error creating Indexes in a transaction

### ISSUE THREAD

**Issue by mattleibow** [mattleibow/Mono.Data.Sqlite.Orm#7]
Currently csharp-sqlite has a security exception when trying to create indexes within a transaction. This occur during the CreateTable method. Currently this can be avoided be setting the createIngexes parameter to false, and then manually creating the indexes after the transaction has been committed.

Usual method:

```
db.CreateTable<IndexedTable>();
```

workaround for SL:

```
db.CreateTable<IndexedTable>(false);
// the indexes
TableMapping map = db.GetMapping<IndexedTable>();
foreach (var index in map.Indexes)
{
    db.Execute(index.GetCreateSql(map.TableName));
}
```

**Comment by mattleibow** [comment]
Exception:

```
System.Security.SecurityException was unhandled by user code
File operation not permitted. Access to path '' is denied.
```

Stack trace:

```
at System.IO.FileSecurityState.EnsureState()
at System.IO.Path.GetTempPath()
at Community.CsharpSqlite.Sqlite3.getTempname(Int32 nBuf, StringBuilder zBuf)
at Community.CsharpSqlite.Sqlite3.winOpen(sqlite3_vfs pVfs, String zName, sqlite3_file pFile, Int32 flags, Int32& pOutFlags)
at Community.CsharpSqlite.Sqlite3.sqlite3OsOpen(sqlite3_vfs pVfs, String zPath, sqlite3_file pFile, Int32 flags, Int32& pFlagsOut)
at Community.CsharpSqlite.Sqlite3.pagerOpentemp(Pager pPager, sqlite3_file& pFile, Int32 vfsFlags)
at Community.CsharpSqlite.Sqlite3.openSubJournal(Pager pPager)
at Community.CsharpSqlite.Sqlite3.subjournalPage(PgHdr pPg)
at Community.CsharpSqlite.Sqlite3.pager_write(PgHdr pPg)
at Community.CsharpSqlite.Sqlite3.sqlite3PagerWrite(PgHdr pDbPage)
at Community.CsharpSqlite.Sqlite3.allocateBtreePage(BtShared pBt, MemPage& ppPage, UInt32& pPgno, UInt32 nearby, Byte exact)
at Community.CsharpSqlite.Sqlite3.btreeCreateTable(Btree p, Int32& piTable, Int32 createTabFlags)
at Community.CsharpSqlite.Sqlite3.sqlite3BtreeCreateTable(Btree p, Int32& piTable, Int32 flags)
at Community.CsharpSqlite.Sqlite3.sqlite3VdbeExec(Vdbe p)
at Community.CsharpSqlite.Sqlite3.sqlite3Step(Vdbe p)
at Community.CsharpSqlite.Sqlite3.sqlite3_step(Vdbe pStmt)
at Mono.Data.Sqlite.SQLite3.Step(SqliteStatement stmt)
at Mono.Data.Sqlite.SqliteDataReader.NextResult()
at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Mono.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
at Mono.Data.Sqlite.Orm.SqliteSession.Execute(String query, Object[] args)
at Mono.Data.Sqlite.Orm.SqliteSession.<>c__DisplayClass2a.<CreateTable>b__29(Index index)
at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
at System.Linq.Enumerable.Sum(IEnumerable`1 source)
at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
at Mono.Data.Sqlite.Orm.SqliteSession.CreateTable(TableMapping map)
at Mono.Data.Sqlite.Orm.SqliteSession.CreateTable[T]()
at Mono.Data.Sqlite.Orm.Tests.CreateTableTest.CreateIndexedTable()
```

**Comment by mattleibow** [comment]
This issue is opened at [csharp-sqlite issue 150](https://code.google.com/p/csharp-sqlite/issues/detail?id=150)

**Comment by asavasamuel** [comment]
mattleibow 

Here is an ORM that works with Sqlite
https://www.kellermansoftware.com/p-47-net-data-access-layer.aspx

**Comment by mattleibow** [comment]
This has been fixed in csharp-sqlite
